# Generated by Django 4.2.7 on 2023-12-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
