# Generated by Django 4.2.7 on 2024-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordertotripmapping',
            options={},
        ),
        migrations.AddField(
            model_name='trip',
            name='maintanance_reason',
            field=models.CharField(default='N/A'),
        ),
    ]
