# Generated by Django 4.2.7 on 2024-01-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options_alter_ordertotripmapping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='maintanance_reason',
        ),
    ]
