# Generated by Django 4.2.7 on 2024-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_gst_order_gst_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gst_amount',
            field=models.IntegerField(default=0),
        ),
    ]
