# Generated by Django 4.2.7 on 2024-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_gst_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='maintanance',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
