# Generated by Django 4.2.7 on 2024-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_trip_maintanance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField(db_comment='Maintenance activity registered date')),
                ('maintenance_name', models.CharField()),
                ('charges', models.FloatField()),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
