# Generated by Django 4.2.7 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_maintenance_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='balance_with_gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_expenses',
            field=models.FloatField(default=0),
        ),
    ]
