# Generated by Django 4.2.7 on 2024-01-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_trip_balance_with_gst_trip_total_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='next_service_km_due',
            field=models.IntegerField(db_comment='How many kilometers are remaining for next service due?', default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
    ]
