# Generated by Django 4.2.7 on 2024-01-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehicle_next_service_km_due_alter_order_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='emis_tenure',
            field=models.IntegerField(db_comment='Total No. of Months EMI is taken for', default=0),
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emi_date', models.DateField(db_comment='EMI paid date or EMI submitted date')),
                ('emi_type', models.CharField(choices=[('truck', 'truck'), ('loan', 'loan')], default='truck', max_length=5, verbose_name='EMI type')),
                ('emi_amount', models.FloatField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehicle')),
            ],
            options={
                'db_table': 'emi',
            },
        ),
    ]
